HEADERS = {
    'stdio.h':{
        'printf':{
            'arg':None,
            'return_type':'int',
            'variables':[]
        },
        'scanf':{
            'arg':None,
            'return_type':'int',
            'variables':[]
        },
        'gets':{
            'arg':None,
            'return_type':'int',
            'variables':[]
        },
        'puts':{
            'arg':None,
            'return_type':'int',
            'variables':[]
        },
    },
    'string.h':{
        'strlen':{
            'arg':1,
            'return_type':'int',
            'variables':[]
        },
        'strcat':{
            'arg':1,
            'return_type':'int',
            'variables':[]
        },
    },
    'conio.h':{
        'clrscr':{
            'arg':0,
            'return_type':'void',
            'variables':[]
        },
        'getch':{
            'arg':0,
            'return_type':'int',
            'variables':[]
        }
    },
    'math.h':{
        'round':{
            'arg':1,
            'return_type':'int',
            'variables':[]
        },
        'floor':{
            'arg':1,
            'return_type':'int',
            'variables':[]
        },
        'ceil':{
            'arg':1,
            'return_type':'int',
            'variables':[]
        },
        'truncat':{
            'arg':1,
            'return_type':'int',
            'variables':[]
        }
    },
}