HEADERS = {
    'stdio.h':{
        'printf':{},
        'scanf':{},
        'gets':{},
        'puts':{},
    },
    'string.h':{
        'strlen':{
            'arg':1,
        },
        'strcat':{
            'arg':1,
        },
    },
    'conio.h':{
        'clrscr':{
            'arg':0,
        },
        'getch':{
            'arg':0,
        }
    },
    'math.h':{
        'round':{
            'arg':1,
        },
        'floor':{
            'arg':1
        },
        'ceil':{
            'arg':1
        },
        'truncat':{
            'arg':1
        }
    },
}